steps:

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/identityserver', 
      '-f', 'Dockerfile.Core', 
      '.']
  
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/identityserver']

# Deploy container image to Cloud Run
# NB. Requires IAM permissions to be configured first, see
#     https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-cloud-run#required_iam_permissions
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'run', 
      'deploy', 
      'identityserver', 
      '--image', 'gcr.io/$PROJECT_ID/identityserver', 
      '--region', 'europe-west4', 
      '--platform', 'managed', 
      '--allow-unauthenticated']

images:
- gcr.io/$PROJECT_ID/identityserver